### PR TITLE
FIX: warning: constant ::Fixnum is deprecated

### PR DESCRIPTION
**Pull request by mtunjic**
Just small gems update to fix deprecation warning.

### CODE REVIEW

**Comment by roman-zaharenkov** [comment]
👍

**Comment by roman-zaharenkov** [comment]
Is there any chance to get it released soon?

**Comment by kiela** [comment]
@mtunjic Please remove commit for bumping version.

**Comment by acapro** [comment]
Any reason this hasn't been merged yet?

**Comment by taher435** [comment]
Please merge this as my logs are getting polluted by unnecessary `FixNum` warnings.

**Comment by khanotations** [comment]
Would really appreciate a merge here!

**Comment by dreamfall** [comment]
Pretty please! :shipit:

**Comment by ibarria0** [comment]
bump

**Comment by khanotations** [comment]
I have a fork here that might be useful: https://github.com/iExperience/forgery

**Comment by brandonarbini** [comment]
So sorry everyone. I just fixed it in #84.

**Pull request closed without merging**
